version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=88795842
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    container_name: igmaApi
    ports:
      - "8002:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn run:app --reload --workers 1 --host 0.0.0.0 --port 8000

volumes:
  postgres-volume: